Repository VedantKhairnar/Cheat-Sheets, pull requests merged in 2020-10, with the labels that each got.

#9 .py
  py/CheatSheet-Python-1_-Keywords1.pdf
Labels: hacktoberfest

#11 :sparkles: updated CodeWars Py Practice Questions
  Competitive Programming/CodeWars Practice Questions/Find Product.py
  Competitive Programming/CodeWars Practice Questions/Find the next perfect square.py
  Competitive Programming/CodeWars Practice Questions/Growth of a Population.py
  Competitive Programming/CodeWars Practice Questions/Isograms.py
  Competitive Programming/CodeWars Practice Questions/Molecule to atoms.py
Labels: hacktoberfest

#14 Excel-cheat-sheet
  Excel/excel-cheat-sheet-Microsoft.pdf
Labels: hacktoberfest

#15 Update README.md
  README.md
Labels: hacktoberfest

#13 An awesome cheat-sheet for flask
  flask_cheatsheet.pdf
Labels: hacktoberfest

#16 11 PDFs added
  Docker & Kubernetes/Docker commands.jpg
  Docker & Kubernetes/Kubernetes commands.pdf
  Docker & Kubernetes/docker build-share-run.pdf
  Docker & Kubernetes/docker-commands.pdf
  Docker & Kubernetes/docker-kubernetes-service.pdf
  Docker & Kubernetes/kubernetes.pdf
  Interview Questions/Python Coding-Interview-Questions.pdf
  Machine Learning/Supervised Machine Learning 1.pdf
  Python/Python Data-Structures.pdf
  Python/Python Keywords.pdf
  Python/python_cheat_sheet_v1.pdf
Labels: hacktoberfest

#17 PDF merge in Docker & Kubernetes
  Docker & Kubernetes/Kubernetes-.webp
  Docker & Kubernetes/Kubernetes-07182019.pdf
  Docker & Kubernetes/cheatsheet-kubernetes-A4.pdf
  Docker & Kubernetes/jwilkinson_kubernetes.pdf
Labels: hacktoberfest

#18 Data Science Cheat Sheet for Business Leaders
  Data Science/Data Science Cheat Sheet for Business Leaders.pdf
Labels: hacktoberfest, hacktoberfest2020

#19 spaCy Cheat Sheet Advanced NLP in Python
  NLP/spaCy Cheat Sheet Advanced NLP in Python.pdf
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#20 Added Kubernetes-Intellipaat
  DevOps/Kubernetes-Cheat-Sheet.pdf
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#21 Added ACM-ICPC Cheat Sheet
  Competitive Programming/ACM-ICPC.pdf
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020

#22 Add files via upload
  Mathematics/sequences-and-series.pdf
Labels: hacktoberfest-accepted

#24 calculus
  Mathematics/calculus.pdf
  Mathematics/discrete-math.pdf
Labels: hacktoberfest-accepted
